### ISSUE TITLE
Changing project settings locks out part of UI in Beta 6

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#124] opened 2014-01-05 19:21 UTC
If I change the project settings (in this case I unchecked the jQuery option from jshint but I've seen this happen for other changes as well), then when I return to the main interface, some parts are disabled. CK continues to function (e.g. the server still runs, CK still processes file changes), but I can no longer access the project settings or the assets functionality. Quitting and restarting fixes things. Here's a screen shot where you can see that the Assets and Project settings buttons are disabled.

![screen shot 2014-01-05 at 2 17 09 pm](https://f.cloud.github.com/assets/1731910/1847234/6dab2bfe-763e-11e3-80b1-d30507d548c6.png)

cf this screen shot where they're enabled to see the difference.

![screen shot 2014-01-05 at 2 21 19 pm](https://f.cloud.github.com/assets/1731910/1847236/93028b04-763e-11e3-92f2-4053d538aa72.png)

**Comment by sathomas** [comment] 2014-01-05 19:25
Also, just noticed that the change I tried to make (unchecking jQuery) didn't stick.

**Comment by bdkjones** [comment] 2014-01-05 19:33
I can't reproduce this over here. Please take a screencast showing the full steps to reproduce.

**Comment by sathomas** [comment] 2014-01-05 19:41
I don't have a screencast app, but the steps are trivially simple:
1. Launch CK; wait for it to refresh project (takes several seconds)
2. Click on the project settings gear icon
3. Click on JSHint under Syntax Checkers
4. Scroll down to Environments, jquery is selected by default
5. Click on jquery to de-select it.
6. Click Close button

Voila. Project settings and assets are now locked an un-modifiable.

**Comment by sathomas** [comment] 2014-01-05 19:43
Link to zipped version of project is https://www.dropbox.com/s/suhsd0ghb9ypgrg/atltrails.zip but the project file is huge so it's going to take Dropbox several minutes to upload it.

**Comment by sathomas** [comment] 2014-01-05 20:01
Okay, this motivated me just enough to look into screen capture apps. Here's a screen capture, beginning when CK is first launched.

https://www.dropbox.com/s/zbnf6bhgez3gv91/CK.mov

**Comment by bdkjones** [comment] 2014-01-06 02:57
I can't reproduce this on any of my test projects. I'm downloading yours now to try it on my end.

**Comment by sathomas** [comment] 2014-01-06 11:32
As a note, the problem happened to me this morning without using the project settings. This time I was just editing code and saving as normal. Specifically, I edited and saved `initial.scss` which compiled to `_initial.css` correctly. That file, however, is itself included in `index.kit`. Perhaps this is related to #97

**Comment by bdkjones** [comment] 2014-01-07 02:11
What hardware are you running on? I can't reproduce this issue on my end. 

Has anyone else run into the same problem?

**Comment by sathomas** [comment] 2014-01-07 12:51
MBAir 2012, 4GB RAM

**Comment by sathomas** [comment] 2014-01-07 12:58
Still happens with Beta 6. 100% reproducible on my system

**Comment by sathomas** [comment] 2014-01-07 13:24
Blew away all CK data (caches, configs, preferences, and anything else I could find) and that seems to have cleared up the problem for now.

**Comment by sathomas** [comment] 2014-01-07 13:45
Might this be a duplicate of #108?

**Comment by sathomas** [comment] 2014-01-07 13:50
Here's the `codekit.config` that was causing the error: https://www.dropbox.com/s/x104vm0kmcpoje4/config.codekit.bad

And here's the new `codekit.config` that was created when reloading the project from scratch. Ideally, the settings would be identical, but I'm sure I didn't reproduce the original settings exactly: https://www.dropbox.com/s/afcjoezjy0oo1lm/config.codekit

**Comment by sathomas** [comment] 2014-01-08 12:52
Got the same problem when launching beta 7 for the first time, but shift-startup seemed to clear it up.

**Comment by bdkjones** [comment] 2014-01-11 18:42
Do you guys have OS X set to "always show scroll bars"?

**Comment by sathomas** [comment] 2014-01-11 21:03
Nope.

**Comment by bdkjones** [comment] 2014-01-12 05:24
This should be fixed in Beta 9. Hopefully. 

Pretty sure it was related to #143

**Closed as completed by bdkjones** 2014-01-12 05:24 UTC
