### ISSUE TITLE
Weird UI Issues

### ISSUE THREAD

**Issue by devilskitchen** [bdkjones/CodeKit2#70] opened 2013-12-20 10:13 UTC
I am finding some weird interface bugs in CK2—even just browsing through the Project Settings (screenshots attached). The grey dotted texture seems to crop up particularly in General and Hooks and overlays the tops of the options.

![screen shot 2013-12-20 at 09 56 35](https://f.cloud.github.com/assets/1190864/1789633/d3f03572-695e-11e3-9f8f-3f9acf2c7328.png)
![screen shot 2013-12-20 at 09 50 12](https://f.cloud.github.com/assets/1190864/1789639/f28d659a-695e-11e3-86ea-1485072b8dba.png)
![screen shot 2013-12-20 at 09 48 45](https://f.cloud.github.com/assets/1190864/1789641/014f8ac2-695f-11e3-93ce-43bf6469a766.png)

Sometimes there's an odd gap at the top of the panels...
![screen shot 2013-12-20 at 09 48 30](https://f.cloud.github.com/assets/1190864/1789645/196555ba-695f-11e3-8c1d-b20d85699ace.png)
... and sometimes there's not enough gap, so you can't see the top options...
![screen shot 2013-12-20 at 09 39 34](https://f.cloud.github.com/assets/1190864/1789648/2d878e5a-695f-11e3-9992-4ae3fe6b69b9.png)

[Mac Mini 2.3GHz i5, 8GB RAM, Mac OS X Mavericks]

**Comment by bdkjones** [comment] 2013-12-20 10:14
Closed as a duplicate of a bug already fixed.

Please search issues (including closed issues) before posting bugs.

**Closed as completed by bdkjones** 2013-12-20 10:14 UTC
