### ISSUE TITLE
Wrong File Events on Remote Disks

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#189] opened 2014-01-23 13:02 UTC
When I save anything that needs to be compiled in the latest beta, the project just refreshes, then ignores everything, allowing you to add the project again and again.

Proof Video: http://cl.ly/TWAy

When trying to add files to it to, you get this message:

![screen shot 2014-01-23 at 12 44 23](https://f.cloud.github.com/assets/1001935/1984565/6e6e5356-842e-11e3-89fe-9ac6055077f5.png)

**Comment by bdkjones** [comment] 2014-01-23 15:55
Again, DETAILS are what matter in bug reports. I need a ton of them.

What OS are you on?
What IDE are you saving the file with?
Is the project on a remote disk or a local one?
Is the project folder in Dropbox or some other syncing service?
What have you tried to fix this?
Why is everyone else working just fine --- what makes your setup different?

DETAILS!

**Comment by yratof** [comment] 2014-01-23 16:23
Some details:
- OSX 10.9.1
- Using Coda 2.0.12 to save the files
- Remote Disk, using a mac mini located in the other room, connected via Ethernet, to which I am the admin and have access to all the files.
- No, the files/folders are not in a syncing service, just a normal folder, and I'm the only user looking at it.
- Moving the folder to the mac locally fixes the issue, so it seems to be something with the remote set up and how it looks at the files that trips it up
  - Not working local, working over a network to get the files.

Also Tried holding shift several times, restarting all software and hardware.

**Comment by C-Benz** [comment] 2014-01-23 17:47
I have this same issue with a similar setup. My computer and Mac Mini server are running the latest version of Mavericks. Mac Mini runs Mamp Pro with ghosts configured properly. I'm saving scss files in latest version of Coda.

Interestingly, last night I wanted to try something kind of out of the norm. I used Transmit to mount a remote disk locally thus allowing me to have codekit monitor the scss file. This same thing started happening intermittently. Sometimes it worked, sometimes it didn't. I assumed it was because of the way I mounted the remote server as a disk. I didn't really care too much as this is not my normal workflow but wonder if the two are related.

**Comment by bdkjones** [comment] 2014-01-24 01:19
Okay, so the issue is the remote disk. 

How are you sharing the Mac Mini? SMB or AFP?

**Comment by C-Benz** [comment] 2014-01-24 02:29
Sorry vhosts not ghosts in post above. Damn you autocorrect.

I would assume it's using SMB2 since I read that's the default when both machines are on mavericks. Is there a way to verify that?

**Comment by yratof** [comment] 2014-01-31 00:01
Yeah, both systems on Mavericks, so I connect to the Mac Mini via SMB2.

The mac shows up in the sidebar of finder, it's logged in and "remember me"'d. Hosts all files that I'm working on.

**Comment by bdkjones** [comment] 2014-02-01 06:41
Well guys, I borrowed my friend's Mac Mini and created the exact setup you've described above. I have a simple HTML/CSS site in a shared folder on the Mac Mini. I log into the mini from my machine, add that remote site to CodeKit, and then save a Sass file. It compiles correctly and reloads the browser just fine.

If you're seeing the error in the screenshot, it's likely that the connection to your remote server is of poor quality. Is this all being done over WiFi? If so, try plugging your Mac Mini into your router with an ethernet cable and turning off its WiFi. (Same for your Mac, if able.)

On my end, adding the remote project took a long time (roughly 40 seconds). Adding the same project when it's on my Mac's disk is instantaneous. The reality is that CodeKit is a file-watching-and-responding app. ANY app that does those tasks is going to have trouble when you start introducing a slow network. 

As it stands, I can't reproduce this issue. Try the steps above and see if that resolves things on your end. Use Shift-Start to start fresh each time you try. 

That said, if you disconnect the remote disk suddenly, CodeKit is currently less-than-graceful about it. I'm going to see if I can make that event less painful.

**Comment by yratof** [comment] 2014-02-01 13:35
All my macs are wired, nothing over over wifi. Is your Mac mini a server, or have the server app? Give yourself a new user on the server app and give yourself all the permissions, then login as that user and try that way. It compiles for me too, but it's when it it suddenly starts buggin that it happens. I'll try and log more information about what I do exactly when it happens.

This might be a factors too, we have two macs using codekit specifically, one guy using codekit 1 and me on the beta, we don't work with the same folders, but I'm the same network.

**Comment by bdkjones** [comment] 2014-02-01 19:25
The Mac Mini I have is running Mavericks, but not OS X Server. 

As for CK1 and CK2 looking at the same network: it's not an issue so long as you're not looking at the same files. Still, have the CK1 guy stop accessing the remote disk and test it that way to eliminate the possibility. 

I need a demo project (zipped, with a download link here) and exact steps to reproduce what you're seeing. Please get that to me quickly --- I can only borrow my buddy's Mac Mini for a few more days.

**Comment by yratof** [comment] 2014-02-01 22:55
I'll get hat over to you ASAP, as for osx server, it's now an app, the mini is running mavericks, and server is in the AppStore I believe

**Comment by bdkjones** [comment] 2014-02-03 04:06
I need a demo project and a step-by-step walkthrough ASAP or I'm going to have to close. I can't keep this Mac mini much longer.

**Comment by yratof** [comment] 2014-02-03 11:08
Honestly, I can't replicate it on demand. I've tried all morning to get it to break, and it's just not having it. So I think close this and leave it. If i'm not having issues, then maybe it has either fixed, or something specific has changed on my network (or happens that causes this erratic behaviour ).

If it does happen again. I'll make note of everything that goes on and go through it to find if there are any anomalies, but at this time, nothing bad is happening.

It normally happens by just saving a scss file then codekit starts refreshing rather than compiling. Which is all I can say :/

**Comment by bdkjones** [comment] 2014-02-03 22:07
Okay, closed as unreproducible. 

I'm betting it was probably a slow network. If you're going to work remotely, make sure your network is super, super fast. Streaming Pandora, letting Dropbox sync, or even other users transferring files between machines will all drastically affect the performance of CodeKit over a network.

Again, CodeKit is a file-watching-and-responding app. It needs pretty damn fast and stable access to files to do its job. Anytime that's not the case, you're in for bad things.

**Closed as completed by bdkjones** 2014-02-03 22:07 UTC
Labels: ✘✘✘

**Comment by yratof** [comment] 2014-02-03 22:09
Yeah i know what you mean, our network is completely local though, literally ethernet to a wall, wall to the switch, switch to a  mac mini, we've just got 4 users constantly on the server. one of them might be messing with me and not realising :/

&
