### ISSUE TITLE
Codekit file name inside the zip file isn't Codekit 2

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#2] opened 2013-12-18 10:54 UTC
When i try to copy it into the application folder i get asked if i want to replace the old version. Is it save just to rename the Application to "Codekit 2" or stick the paths within the app also to a few specific ~/library/ locations containing Codekit instead of Codekit2 too? Just to be save.

**Comment by bdkjones** [comment] 2013-12-18 10:56
Yea; it's safe to rename the app whatever you want. OS X uses bundle IDs to uniquely identify Applications; the name in the Finder is just for humans.

**Comment by bdkjones** [comment] 2013-12-18 10:56
I left this set this way because once the app launches, most folks are going to _want_ to replace CodeKit 1 with CodeKit 2. So for now, I'm going to close this issue as intended behavior. Thanks!

**Closed as completed by bdkjones** 2013-12-18 10:56 UTC
