### ISSUE TITLE
Project Settings & Syntax Checkers UI Glitch

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit2#141] opened 2014-01-10 20:12 UTC
[![UI Glitch](http://f.cl.ly/items/37122v1l2b0O2D131336/UI%20Glitch.gif)](http://f.cl.ly/items/37122v1l2b0O2D131336/UI%20Glitch.gif)

Not sure how specifically this is triggered, but here are the symptoms:

**WHAT I WAS DOING:** Got some errors I didn't care about in JSHint, changed some of the JSHint settings and recompiled. Then decided to change some more settings and then:

**WHAT HAPPENS:** When clicking the Project Settings icon, the settings don't come up right away. Click again, and the settings menu comes up, but none of the Syntax Checker pages show any content. Sometimes the scrollbar seems to indicate that the content is _somewhere_, it's just not visually appearing.

**HOW TO FIX IT:** Restarting the app fixes it. Switching projects did not.

**Comment by shshaw** [comment] 2014-01-10 20:49
Figured out how to reproduce this error:
1. Go to **Project Settings**
2. Open up one of the **Syntax Checkers subpages** (JSLint, JSHint, CoffeeLint)
3. Bring up the **Log** _(close out settings, toggle the Log view or try to compile a file that brings up an error)_
4. Click the **Project Settings gear icon** directly from the Log, the first click takes you back to the Files view
5. Click the **Project Settings gear icon** again, and the Settings menu appears sans the settings in the Syntax Checkers subpages

The only way to bring the menu back is restarting the app.

**Comment by bdkjones** [comment] 2014-01-11 01:21
I followed your steps, but can't reproduce this on my end. 

What are your full system stats?

**Comment by shshaw** [comment] 2014-01-11 02:41
2009 Mac Pro running the latest version of Mavericks ( OS X 10.9.1 ).
_Processor_  2 x 2.26 GHz Quad-Core Intel Xeon
_Memory_  16 GB 1066 MHz DDR3 ECC
_Graphics_  NVIDIA GeForce GT 120 512 MB

My last UI issue seemed to be related to having scrollbars enabled, so perhaps that has something to do with it.

I did test it several times, and those steps would reproduce the error each time.

**Comment by bdkjones** [comment] 2014-01-11 07:48
Ah, I’ll try again with “always show scrollbars” enabled.

**Comment by bdkjones** [comment] 2014-01-12 00:59
Ok, I've replicated the behavior on my end. Now to figure out what the hell is causing it.

**Comment by bdkjones** [comment] 2014-01-12 01:18
Fixed in Beta 9.

**Closed as completed by bdkjones** 2014-01-12 01:18 UTC
