### ISSUE TITLE
Bourbon Issues

### ISSUE THREAD

**Issue by C-Benz** [bdkjones/CodeKit2#231] opened 2014-02-03 23:01 UTC
I'm unable to compile a Bourbon project using Libsass on the latest beta. It looks to be an issue with Libsass not being up-to-date enough to handle some stuff in the latest version of Bourbon. It would be cool to allow a user to select which version of Bourbon codekit should use. Otherwise, Bourbon + Libsass is impossible right now. 

Also, I'm still getting the issue where saving a stylesheet in Coda triggers a refresh of the project. The stylesheet then compiles after the refresh unless it uses Bourbon. For Bourbon, the stylesheet hangs on compiling after the project refresh. I usually just quit and then fire up Codekit 1 to compile it. I have Bourbon files installed in my project instead of using Codekit's Bourbon.

My setup is still the Mac Mini Server running Mavericks and OS X Server for my project files. My Macbook Pro is also running Mavericks and Coda 2.0.13.  My network is super fast so I don't think its that. The Mac Mini is plugged directly into an Airport Extreme that broadcasts 802.11ac to my Macbook Pro. Adding a project only takes a few seconds so I wouldn't think its the network speed.

I know this issue is probably near impossible to replicate so I'm thinking of changing up my workflow so all my web files are local or just going back to CK1.  Let me know what info may be helpful cause I would hate for you to have to deal with this problem after launch with others that have a similar setup. Thx

**Comment by bdkjones** [comment] 2014-02-03 23:18
Libsass is 100% beta. If you encounter a problem that can be described as, "Libsass is not working with X", the answer is always going to be: "Then don't use Libsass". Libsass doesn't even have official releases yet; I just update it from the GitHub master branch every few Betas. I'll do it again for 15, but that's unlikely to solve your issue. Libsass is truly an experimental feature.

If you have old Bourbon files installed in your project, you need to delete them and update to the latest release of Bourbon. Older versions of Bourbon hang Sass 3.3, which is the pre-release version of Sass in CodeKit 2. This was resolved in the last update by including a newer version of Bourbon. Since you override CK's internal Bourbon with your own, you'll need to manually update your Bourbon files. In the future, just let CodeKit handle it -- don't install Bourbon files and you won't run into this problem.

As for the Coda refresh on network disk issue: I need a reliable demo project that shows the issue. So far, I haven't been able to reproduce this on my end, so I can't debug it.

**Comment by C-Benz** [comment] 2014-02-04 00:35
I'll mess around with it and see if I can figure it out. I have tried with the latest version Bourbon as well as with no Bourbon files so it would use Codekit's. No dice. Lemme bundle this project up and send it over.

**Comment by C-Benz** [comment] 2014-02-04 22:22
Here's the stylesheets for my project. I've tried adding a folder containing these exact files as a new Codekit project and when I save main.scss, Codekit compiles forever. The copy of Bourbon contained here was installed through Codekit so I assume its the latest.

https://www.dropbox.com/s/8ooxdvzz3jbyz4r/codekit_sample.zip

**Comment by bdkjones** [comment] 2014-02-05 09:15
Okay, I've tested this with the newly-released Beta 15, traced it with the debugger and have discovered that the Sass compiler is hanging for some reason --- it never returns a result to CodeKit, which is why the app just sits and spins forever.

I'm _betting_ this has to do with the pre-release version of Sass 3.3, which does have bugs. I'm going to have to investigate further.

**Comment by bdkjones** [comment] 2014-02-05 09:35
Progress: I pulled down the very latest commit of Sass 3.3 from the master branch (which has hundreds of commits since the official release of Sass3.3.rc2, a few months ago) and tried compiling this project again. This time, Sass did not hang. Instead, it failed to compile cleanly and returned a bunch of deprecation warnings for Bourbon Neat files and the following error:

```
NoMethodError: undefined method `empty?' for nil:NilClass
```

Hell if I know what that means. No file was listed for the error. Try removing Bourbon Neat from this project and see if it compiles at that point.

**Comment by bdkjones** [comment] 2014-02-05 09:42
I tried updating the version of Bourbon Neat in CodeKit (it was previously 1.4.0, the latest is 1.5.0), but that made no difference. I still get the same result as above.

Also, I had previously deleted the entire Bourbon folder out of the project so that CodeKit pulled Bourbon resources from its internal location within the app bundle.

**Comment by C-Benz** [comment] 2014-02-05 18:56
This is so weird! So I took my scss file and stripped literally everything out except for the Neat includes. It seems to be hanging when there are a certain number of these includes. If I remove one, it compiles. If I remove an "@include row" and add another "@include span-columns" it compiles. It seems to be this exact number of each that is causing problems. If I switch to using the bourbon and neat files in the project, it kinda works. 

One other strange thing is, I have set this scss file to compile to the same directory but when it hangs it creates a new directory called "css" anyway.

Would you mind taking a peek at these new project files?

https://www.dropbox.com/s/2pn4d5v3ei0h4op/codekit_test_2.zip

**Comment by bdkjones** [comment] 2014-02-06 08:34
Ok, through a combination of changes to CodeKit and Sass, this issue is now fixed for Beta 16.

**Closed as completed by bdkjones** 2014-02-06 08:34 UTC
Labels: ✘✘✘
