### ISSUE TITLE
Delay auto server refresh

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit2#156] opened 2014-01-14 18:38 UTC
When I start Codekit each day, the internal server will set the address name to a random computer on my network. One day it could be a coworkers upstairs, another day it will be someone else. When this happens, if I click preview, it will not load. 

![screen shot 2014-01-14 at 1 15 45 pm](https://f.cloud.github.com/assets/4323734/1913577/cf2e669e-7d4a-11e3-8e1c-e080fd3d3cdb.png)

The solution right now is to simply give the server a single (sometimes twice) refresh. After doing this it correctly sets the address to my computer.

![screen shot 2014-01-14 at 1 15 58 pm](https://f.cloud.github.com/assets/4323734/1913582/e8c5f70c-7d4a-11e3-87bd-c8997c6b9785.png)

**Comment by bdkjones** [comment] 2014-01-14 18:43
the issue is that your old IP address has been reassigned to your coworker while your Mac was offline. You'll need to restart the server in this case to grab your new DHCP-assigned IP address.

**Comment by ghost** [comment] 2014-01-14 18:47
This happens each time I close and reopen Codekit, regardless of whether my computer is restarted or not.

**Comment by bdkjones** [comment] 2014-01-14 18:50
What is your network setup? Are you connecting via wi-fi, ethernet, etc. Is your router set up to use DCHP or do you have assigned IPs?

**Comment by ghost** [comment] 2014-01-14 21:29
I'm on ethernet. But it also happens when i'm on wifi. We use DHCP.

**Comment by bdkjones** [comment] 2014-01-15 06:41
Okay, in Beta 10 I've increased the delay between when the system receives a change in network status and when CodeKit responds to that by updating its server information. It was previously 1.0 seconds. It is now 2.5 seconds.

This should, hopefully, fix this issue. It's a bit complex: OS X issues about 3-5 "network status changed" events each time you wake your Mac up from sleep or turn on/off wifi. It's a bit of a mess, really.

**Closed as completed by bdkjones** 2014-01-15 06:41 UTC
