### ISSUE TITLE
autoprefixer doesn't seem to run — Beta 8

### ISSUE THREAD

**Issue by pmeissner** [bdkjones/CodeKit2#153] opened 2014-01-14 13:37 UTC
Using libsass and with autoprefixer checked and set to:
`> 1%, last 2 versions, ff 17, opera 12.1`
My CSS:
`background-image: linear-gradient(top, #FFFFFF 0%, #000000 100%);`
And my output is:
`background-image: linear-gradient(top, #FFFFFF 0%, #000000 100%);`
And I would expect:
`background-image: -webkit-linear-gradient(top, #FFFFFF 0%, #000000 100%);`

No error messages.

**Comment by pmeissner** [comment] 2014-01-14 14:01
After fiddling around codekit is finally giving me an error message — progress?

"Autoprefixer failed to process the CSS file. It returned this error message: Can't parse CSS: Unclosed block at line 4971:3 in /Users/phil/Sites/triplescoop/css/app.css"

I'm guessing that this is related to this issue? https://github.com/bdkjones/codekit2beta/issues/115

![screen shot 2014-01-14 at 8 57 01 am](https://f.cloud.github.com/assets/392386/1910972/12bbb4f6-7d24-11e3-9d35-0c8dfe88f2d9.png)

**Comment by sathomas** [comment] 2014-01-14 15:16
@pmeissner If you disable libsass does the problem go away? If so, it is almost certainly a duplicate of #115.

**Comment by pmeissner** [comment] 2014-01-14 15:24
The error goes away. But I still can't get autoprefixer to do anything.

**Comment by bdkjones** [comment] 2014-01-14 18:15
Duplicate of #115.

**Closed as completed by bdkjones** 2014-01-14 18:15 UTC
