### ISSUE TITLE
CodeKit server issues

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit2#589] opened 2015-11-02 06:17 UTC
Hi Bryan!

I Started having big issues last week half way through a project, when CodeKit's auto-reload went bad. After saving an asset, the browser most often will start waiting for an available socket before CodeKit will inject the new files. Sometimes this can take up to 20 seconds.

I'm mainly accessing CodeKit's server through `localhost:5757`, but issues also remain accessing through IP-address and Bonjour name.

The system hasn't been modified recently apart from latest version bumps of Chrome and Firefox (both after issues started appearing). I have also already ruled out possible local networking issues.

I'm happy to provide you with additional details and eager to sort this out rather quickly, since the issue has a big footprint on my workflow.

Cheers!

**Comment by bdkjones** [comment] 2015-11-02 06:19
How, precisely, have you ruled out "local networking issues"?

**Comment by indrekpaas** [comment] 2015-11-02 06:39
I guess generally -- I'm connected through ethernet as opposed to wifi, ping tests have no packets lost and other connections don't have difficulties.

Let me know if there's something more precise you'd recommend.

Cheers!

**Comment by bdkjones** [comment] 2015-11-02 07:01
None of those things have to do with name resolution. Try these three things:
1. Use WiFi instead of ethernet. Same symptoms?
2. Try a different network. Coffeeshop, work, etc.
3. Reboot your networking devices (router, modem, etc.)

-Bryan

**Comment by indrekpaas** [comment] 2015-11-10 01:33
Closing this, as the issue has resolved itself as mysteriously as it appeared. Unfortunately I didn't find out the cause.

**Closed as completed by indrekpaas** 2015-11-10 01:33 UTC

**Comment by sharvilak11** [comment] 2018-02-26 13:41
I am facing the same issue at the moment.
Chrome is giving me **Waiting for Available socket** , although it works fine in Firefox. Uninstalled chrome, deleted all chrome associated data. Still no success!

Did you get to know anytime later what had happened ? @indrekpaas

**Comment by bdkjones** [comment] 2018-02-26 15:10
Have you rebooted?
