### ISSUE TITLE
Assest don't remember the chosen column to sort by after restart

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#45] opened 2013-12-18 22:39 UTC
- Go to the Assets pane
- Click e.g. on the name column, that the list is sorted alphabetically
- Quit Codekit
- Restart Codekit
- Go to Assets pane again
- The sort order got reverted again and lost the chosen alphabetical by name

**Comment by mdavis1982** [comment] 2013-12-18 22:42
@bdkjones I've marked this as a bug - but is this expected behaviour?

**Comment by bdkjones** [comment] 2013-12-19 23:39
Yes. This is expected behavior. CodeKit always sorts by the number of stars because Bower is so full of junk it's useless to sort any other way.

**Closed as completed by bdkjones** 2013-12-19 23:39 UTC
Labels: ✘✘, [A] User Interface, [P] Pending Confirmation
