### ISSUE TITLE
Less combined (inline) files are not mignified

### ISSUE THREAD

**Issue by nicolastaffin** [bdkjones/CodeKit2#544] opened 2015-04-14 15:16 UTC
Hi, coming from : https://github.com/bdkjones/CodeKit/issues/463
(i wanted to combine & mignify several dev LESS files into one prod CSS file + map)
it seems that the LESS output mignification options are not applied after successful import
@import (inline) url("stylesheet.less");
Maybe i did it wrong.
Thanks anyway for your GREAT work

**Comment by bdkjones** [comment] 2015-04-14 17:39
Can you show me what the actual output is and what you expect the output to be?

**Comment by nicolastaffin** [comment] 2015-04-15 21:37
stylesheet.less content :
@import (inline) url("stylesheet2.less");
@import (inline) url("stylesheet3.less");

output: 2 files
stylesheet.css
stylesheet.map

stylesheet.css content :

```
selector {
    property: value;
    property: value;
}
anotherselector {
    property: value;
    property: value;
}
```

is not minified despite "Remove whitespace" is selected in the project settings
and i expected:

```
selector{property:value;property:value;}anotherselector{property:value;property:value;}
```

**Comment by bdkjones** [comment] 2015-04-16 03:14
Ah, yea. This is a problem in the 2.0 version of Less. Should be resolved with the next update, which will include the latest version of Less.

**Comment by nicolastaffin** [comment] 2015-04-16 08:00
Ok thanks for your answer.

**Comment by bdkjones** [comment] 2015-04-27 04:08
Should be fixed in 2.3

**Closed as completed by bdkjones** 2015-04-27 04:08 UTC

**Comment by nicolastaffin** [comment] 2015-04-27 04:47
oops, sorry, you can reopen the issue cause it is not :-( I just checked when notified you were around.

**Comment by nicolastaffin** [comment] 2015-04-27 04:54
Okay, the "compressed" option works and not the "remove whitespace" one.

**Comment by bdkjones** [comment] 2015-04-27 05:12
You’re going to have to check with the Less.js team, because I think this is working as intended.

**Comment by nicolastaffin** [comment] 2015-05-07 09:17
With your latest version i now get this message. Useful ?
"Compiled successfully, but with warnings:
The compress option has been deprecated. We recommend you use a dedicated css minifier, for instance see less-plugin-clean-css."
