### ISSUE TITLE
Browser refresh at times just stops

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#88] opened 2013-12-22 22:19 UTC
Working with Wordpress, Mamp Pro.  Browser (safari 7.01) pointed to the 5757 link.

As I work on less file, CK compiles, but browser not updated.  Have to force reload to see changes.

Beta 3.

**Comment by hlissner** [comment] 2013-12-23 00:40
I suspect this is caused by Wordpress's permalinks and is related to #57 — correct me if I'm wrong.

**Comment by smlombardi** [comment] 2013-12-23 02:04
Could be.  Had to go back to CK 1 while working with WP on deadline, too annoying.

**Comment by mdavis1982** [comment] 2013-12-23 11:25
This is a duplicate (and related to) #57 as @hlissner says. Closing.

**Closed as completed by mdavis1982** 2013-12-23 11:25 UTC
Labels: [S] Rejected, ✘✘, [A] Server
