### ISSUE TITLE
Cannot browse to the [computer name].local:5757 address on Android devices

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit2#38] opened 2013-12-18 20:57 UTC
When I browse to my computers address on our testing iPad's and other laptops (PC and Mac) I am able to get to my project just fine. 

But for some reason I am not able to get to my project through an Android device using the Chrome browser. 

I've tried with a Nexus 7 and and Nexus 5 and both won't get to my computer. The error is "Oops! Google Chrome could not find jons-macbook-pro.local:5757/home.html".

They are on the same network.

**Comment by mdavis1982** [comment] 2013-12-18 21:01
I think this is an issue with the Android device's browser, and not a CodeKit-specific issue.

Try entering: `http://jons-macbook-pro.local:5757/home.html` manually (incude the `http` part). I also sometimes get this issue with Chrome on Desktop.

**Comment by ghost** [comment] 2013-12-18 21:08
I've tried using http:// in front of it and it still does not work.

**Comment by mdavis1982** [comment] 2013-12-18 21:09
This is a documented Android bug. https://code.google.com/p/android/issues/detail?id=8030

@bdkjones Do you want me to reopen this issue?

**Comment by ghost** [comment] 2013-12-18 21:18
I'm not quite sure it is the same bug. I've also tried [local ip address].local:5757 and it doesn't work either. 

I believe that bug is specifically for name resolution no? Maybe i'm wrong. Either way, it is still important to find a solution or a way around this bug.

**Comment by mdavis1982** [comment] 2013-12-18 21:22
@JonDagata http://android.stackexchange.com/questions/49188/how-to-get-mdns-working-for-chrome-on-android

Could you try that solution and let us know if it works please? Thanks

**Comment by ghost** [comment] 2013-12-18 21:26
I will try that solution. 

The chrome browser on an iPad works just fine.

**Comment by ghost** [comment] 2013-12-18 21:31
When I went to the DNS entry fields they were both accurate. I tried setting it to static and leaving it as the correct DNS but it still didn't work.

**Comment by mdavis1982** [comment] 2013-12-18 21:33
@JonDagata Did you change the DNS to the router address?

**Comment by ghost** [comment] 2013-12-18 21:36
Yes, it was the same DNS IP that my laptop was connected to as well.

**Comment by mdavis1982** [comment] 2013-12-18 21:38
That's not correct... Apple devices have built-in support for mDNS. You would need to change the DNS to point to somewhere on your local network to make this work in Android. Can you try adding your router address for your DNS in Android, and if that doesn't work the IP of the machine running CodeKit. Thanks

**Comment by bdkjones** [comment] 2013-12-18 21:40
Damn.

Are all Android folks going to have to follow this process? I don't have any Android devices for testing; I just assumed Google would have their act together.

**Comment by mdavis1982** [comment] 2013-12-18 21:41
@bdkjones Yup... Google insist on enforcing that everything goes through their DNS (8.8.8.8) by default - and .local domains don't resolve properly. It sucks.

**Comment by ghost** [comment] 2013-12-18 21:46
I tried setting the DNS to both my local computer running Codekit address and also the routers IP address. 

No luck.

**Comment by mdavis1982** [comment] 2013-12-18 21:48
It's definitely a known Android bug...

https://www.google.com/search?q=android+.local+domain

I'm not sure there's much that can be done about it short of throwing things at the Google building.

@bdkjones Any ideas?

**Comment by ghost** [comment] 2013-12-18 21:58
http://www.androidpolice.com/2012/11/21/google-acknowledges-2-5-year-old-networking-bug-promises-fix-in-next-android-version/

**Comment by ghost** [comment] 2013-12-18 21:59
My personal Nexus 5 still has this bug. Running 4.4.2

Even if it is fixed in a future update though, that still is going to be trouble for testing on previous generation devices in my companies mobile testing lab.

**Comment by mdavis1982** [comment] 2013-12-18 22:05
@JonDagata I understand that this would be a pain in the ass for older devices - but the issue is with Android and there's not a lot that CodeKit can do about it. Does it work if you put the IP address of the machine that has CodeKit in the browser?

**Comment by ghost** [comment] 2013-12-18 22:08
Yeah, I understand. And nope.

**Comment by mdavis1982** [comment] 2013-12-18 22:17
@bdkjones I assume that as this is an Android bug, that users have come up with their own ways of testing local sites on those devices. I don't think there's much that can be done here - and I don't think it's worth crippling the feature for devices that do provide the correct DNS functionality. Shall I close this issue?

**Comment by ghost** [comment] 2013-12-18 22:34
@bdkjones @mdavis1982 

I found a solution! With the help of a coworker (thanks @thefivetoes! ) I realized that when I was typing my IP address in as this:

http://192.168.16.60.local:5757/home.html

it would not work.

But if I remove the .local and make it like this:

http://192.168.16.60:5757/home.html

It does work!

HOWEVER,

Doing it this way requires me to refresh manually each time a change is made to see the changes. It does not auto refresh.

So maybe this isn't a solution but rather a work around.

**Comment by mdavis1982** [comment] 2013-12-18 22:36
@JonDagata Excellent news! I did mean just browsing to the IP address without the `.local` suffix before... I was unsure why that wouldn't work :smile: 

I don't think there's a way to get the auto refreshing to work, to be honest - but at least you can view it manually. I just need @bdkjones to confirm that this constitutes a 'good-enough' workaround, and then I can close the issue.

Thanks for taking the time to report the issue and to try the workarounds :smile:

**Comment by ghost** [comment] 2013-12-18 22:45
Thanks for all your help.

**Comment by mdavis1982** [comment] 2013-12-18 22:46
No problem at all! :smile:

**Closed as completed by mdavis1982** 2013-12-18 22:46 UTC

**Comment by sethta** [comment] 2013-12-20 14:42
I have found an issue with this (not sure if I should create a new ticket or not).

I use WordPress, so I need to make sure "Always use my external server" is checked so my stylesheets and images get served correctly. Unfortunately, when I view my project on my Android pointing to my Mac's local IP address, the site does appear, but those stylesheets and images don't make it.
