### ISSUE TITLE
Help Popup Does Not Always Close

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit2#74] opened 2013-12-20 15:27 UTC
I sometimes have trouble with the help popups that appear when selecting a text input under the project preference pane.

Sometimes they will not disappear when I select another input field causing two help popups to be open at the same time. When this happens I am unable to enter or change any text in the fields. To solve this I close the project preference pane and reopen it. I am then able to edit the text.

**Comment by edwardsdesign** [comment] 2013-12-20 16:36
How to recreate the double popups:
- Open project preferences
- Place your cursor in the input field
- **Tab** to the next field, the first help popup does not close. See screenshot.

![ck2-double-help-popups](https://f.cloud.github.com/assets/867897/1791841/b2bcf94a-6994-11e3-9f04-951d3f16ee9e.png)

How to recreate the issue of not being able to edit the input field value:
- Open project preferences
- Select an input field to get the popup
- Click outside of the CK2 application window (example would be another app window or your desktop)
- When I click back on to the CK2 app I am now unable to enter / change the textfield value.

**Comment by bdkjones** [comment] 2013-12-21 05:39
Thanks for the detailed report; it was written very well.

However, it's a duplicate of an existing issue so I'm going to close it here.

**Closed as completed by bdkjones** 2013-12-21 05:39 UTC
