### ISSUE TITLE
Resources are not being properly loaded in WordPress(like) environments

### ISSUE THREAD

**Issue by johnsardine** [bdkjones/CodeKit2#131] opened 2014-01-08 00:39 UTC
**What's the problem?**

In a WordPress(like) environment, in the sense that the page assets are referenced using the full url, like WordPress does, the resources are not being properly loaded.

**How to reproduce?**

I created a mini sample.
1. Using MAMP, i created a folder inside my sites folder, which is the root of my `http://localhost/` called `codekitsample`, so I ended with this url `http://localhost/codekitsample/`. You can download the project [here](http://cl.ly/TF4f).
2. Add the project to CK, and in `Browser Refreshing > External Server Address` insert `http://localhost/codekitsample/` and check "Use this external server for all requests"
3. Press Preview

The background should be red, but it isn't.

View the source of the page and click on the style.css link on the header, it will return "Ye Olde 404".

While i could create a host for each project on MAMP, I don't do it because i work with other people, and using localhost and sub-folders allows us to maintain the same structure across machines, specially in windows machines where is not as simple to create a host for a project as is in MAMP.

Im using the latest beta, in `Mavericks 10.9.1`, previewing in `Chrome 31.0.1650.57` and using `Coda`.

**Comment by bdkjones** [comment] 2014-01-08 02:23
Do you have MAMP set to run on port 80?

**Comment by bdkjones** [comment] 2014-01-08 02:27
Nevermind. This is indeed a bug on my end. The issue is the subpath; CodeKit is not currently replacing it correctly. I'll fix it.

**Comment by bdkjones** [comment] 2014-01-08 06:15
Fixed in Beta 7. Up in a few minutes.

**Closed as completed by bdkjones** 2014-01-08 06:15 UTC
