### ISSUE TITLE
Compiler errors when using internal Compass compiler

### ISSUE THREAD

**Issue by Veraxus** [bdkjones/CodeKit2#66] opened 2013-12-19 22:56 UTC
Any time I take any action that involves CodeKit's internal Compass compiler, I get errors. Changing CodeKit's preferences to use my own system version of Compass ( _0.12.2 (Alnilam)_ ) resolves this. 

I tried two different scenarios using the internal Compass compiler, and get the same error...
- I add an existing Foundation + Compass project to CodeKit, then make a change to one of the SCSS files. I get the error.
- I attempt to create a new Compass project from within CodeKit. When I click "Install", I get the error.

Here's the error:

```
/Library/Ruby/Gems/2.0.0/gems/sass-3.2.12/lib/sass/script/literal.rb:7:in `<module:Script>': superclass mismatch for class Literal (TypeError)
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.2.12/lib/sass/script/literal.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:2:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:32:in `block in <main>'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:20:in `fallback_load_path'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:31:in `<main>'
```

**Comment by maxlapides** [comment] 2013-12-19 23:03
This is a duplicate of this issue: https://github.com/bdkjones/codekit2beta/issues/11

**Closed as completed** 2013-12-23 11:16 UTC
Labels: [S] Rejected, ✘✘, [A] Processor
