### ISSUE TITLE
Layout - Bad navigation highlight

### ISSUE THREAD

**Issue by chrfickinger** [bdkjones/CodeKit2#392] opened 2014-07-16 05:14 UTC
not so easy to read, lightgrey on green :)

see screenshot

![ck21](https://cloud.githubusercontent.com/assets/91317/3594846/1562320c-0ca8-11e4-9409-3d3632f5b416.jpg)

**Comment by guymeyer** [comment] 2014-07-16 06:04
Would you believe me if I said it was intentional?

Don't believe me.

**Comment by chrfickinger** [comment] 2014-07-16 06:20
JFYI, seems like it doesn't appear every time. Now its white on green like it should be. It was just broken after adding a new project.

**Comment by bdkjones** [comment] 2014-07-16 08:26
I'm not able to reproduce this on my end. Can you give me exact steps to make it happen?

**Comment by chrfickinger** [comment] 2014-07-16 08:45
just 2 clicks:
- create a new google web starter project by clicking on the plus-icon
- choose a project-folder

**Comment by bdkjones** [comment] 2014-09-19 06:36
Fixed in 2.1.3.

**Closed as completed by bdkjones** 2014-09-19 06:36 UTC
