### ISSUE TITLE
CodeKit not compiling compass with local versions installed. (Beta 20)

### ISSUE THREAD

**Issue by noelforte** [bdkjones/CodeKit2#286] opened 2014-03-03 17:45 UTC
**NOTE: This issue is a follow-up to #281.**

I've found that if you install Sass (3.2) and Compass (0.12.x) via `sudo gem install sass compass`, CodeKit refuses to create/compile any Compass projects, even though the compilers are set to use CodeKit's internal versions, and not external compilers. This could be an issue for people who have local versions of Compass and Sass, because it seems like there is a conflict with CodeKit's internals.

![screen shot 2014-03-03 at 12 47 37 pm](https://f.cloud.github.com/assets/2560683/2312432/04245710-a2fc-11e3-87b3-5568038e895f.png)

**Comment by noelforte** [comment] 2014-03-03 21:59
Checked in Beta 20. Still not compiling Compass with local versions present.

**Comment by bdkjones** [comment] 2014-03-04 00:52
Does uninstalling Just sass 3.2 fix this?

-Bryan

**Comment by noelforte** [comment] 2014-03-04 01:11
As far as I'm aware, yes, although I'll have to test again when I'm near a computer in a few hours. 

UPDATE: Uninstalling Sass 3.2 fixes this issue, although if Codekit has Sass 3.2 internally, why does it default to using 3.2 even though the preferences are set to use the internal Sass compiler?

**Comment by bdkjones** [comment] 2014-03-04 10:21
Ok. I "fixed" this by catching the specific error and reforming the message to tell the user that he needs to uninstall older versions of Compass and Sass from his system.

After googling, it appears that that IS the designated fix for this problem.

**Comment by noelforte** [comment] 2014-03-04 18:23
Very good. Thanks!

**Comment by bdkjones** [comment] 2014-03-06 00:28
It is using the internal. The problem is that HAVING 3.2 installed means there’s a conflicting Ruby library on your Mac. For some reason, Ruby grabs that library instead of the one with the newer version of Sass. Don’t ask me why; Ruby is dumb. 

-Bryan

**Comment by justalever** [comment] 2014-06-10 03:48
@bdkjones  I have the same issue as @thenoelforte had, 

Today I installed command line tools to start messing with Ruby. Ruby uses an earlier version of Sass as a dependency. I removed all Sass and Compass from my system that I'm aware of and still get the new error you spoke of or 

"Compass failed to run because your Mac has an older version of Sass and/or Compass installed that conflicts with the newer versions in CodeKit. You must remove all versions of Sass below 3.3.rc6 and all versions of Compass below 1.0.alpha18. Do this at the command line by running 'sudo gem uninstall sass' and 'sudo gem uninstall compass'."

Any insight? My Preferences in CodeKit are - Using CodeKit 2.0.6, Sass version 3.3.8, Compass unkown? - Could this be the issue? I installed compass-0.12.6 (current version) manually but still no luck.
![ck-no-compile](https://cloud.githubusercontent.com/assets/1336971/3225482/09fe3586-f052-11e3-8516-264c06719f77.png)

**Comment by bdkjones** [comment] 2014-06-10 05:36
Yep.

You literally cannot have the older versions of Sass/Compass installed ANYWHERE on your Mac because they have dependencies (older versions of certain other Ruby libraries) that conflict with the newer libraries used by the latest versions. 

This isn't a CodeKit issue; you simply need to wipe all older versions of Sass/Compass from all Ruby environments on your Mac, including any RVM environments and so on.

**Closed as completed by bdkjones** 2014-06-10 05:36 UTC

**Comment by feesh** [comment] 2014-06-19 17:45
Wait, isn't this still a CodeKit issue? I want to be able to have access to SASS and Compass on command line, too. Is there a way in CodeKit to just target those external libraries and use those?

**Comment by bdkjones** [comment] 2014-06-19 22:35
No. 

You can definitely still have Compass and Sass installed at the command line and you can even tell CodeKit to use those local copies (preferences window), but you cannot have old versions of Sass or Compass installed. 

You must install Compass 1.0.0.a19 (using the `--pre` flag) and Sass 3.3+

**Comment by jackmcconnell** [comment] 2014-07-16 12:48
I'm still getting this with the latest version of CodeKit (2.1). 
When trying to install compass into a project via the project settings it gives the error: 

> Compass failed to run because your Mac has an older version of Sass and/or Compass installed that conflicts with the newer versions in CodeKit. You must remove all versions of Sass below 3.3.rc6 and all versions of Compass below 1.0.alpha18. Do this at the command line by running 'sudo gem uninstall sass' and 'sudo gem uninstall compass'.

However, I have removed all traces of Sass and Compass at the command line. 
When performing `sass -v` and `compass -v`both show as 'command not found' but the error in CodeKit still shows. 

Do you know why this might be?

**Comment by bdkjones** [comment] 2014-07-16 19:20
You've still got the dependencies for compass/sass installed in at least one ruby environment.

Nuke all the gems on your Mac in every Ruby environment. That is the only sure-fire way I know to resolve this issue; Ruby is crazy.

**Comment by chorstikus** [comment] 2014-09-24 08:39
@voltronik 

If you are using RVM for your ruby management then switch to your system ruby version
`rvm use system`
and install sass and compass for this version
`sudo gem install sass`
`sudo gem install compass`
This worked for me!

**Comment by jackmcconnell** [comment] 2014-09-24 08:41
@chorstikus Thanks. That would work however, I'd like CodeKit to manage this for me.
