### ISSUE TITLE
Cosmetic issue in log on retina mbp

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#238] opened 2014-02-06 19:13 UTC
See image: 
![screen shot 2014-02-06 at 2 12 32 pm](https://f.cloud.github.com/assets/835148/2102725/c3b2e25c-8f62-11e3-846f-5bdc4571135e.png)

**Comment by smlombardi** [comment] 2014-02-06 19:19
Also, it shows a similar log item now even when it compiles successfully: 
![screen shot 2014-02-06 at 2 18 11 pm](https://f.cloud.github.com/assets/835148/2102790/8dc85bc6-8f63-11e3-99ed-f4bd71e6c08e.png)

**Comment by maxlapides** [comment] 2014-02-06 19:57
This is a duplicate of this old issue: https://github.com/bdkjones/codekit2beta/issues/63

As far as I know, we're still on a hunt for a way to reproduce this issue reliably.

**Comment by bdkjones** [comment] 2014-02-06 22:19
Yep. I can get it every now and then, but I have no idea what causes it and can't get it to happen regularly, so it's virtually impossible to fix. Working on it.

**Comment by bdkjones** [comment] 2014-02-07 00:26
Closed as a duplicate.

**Closed as completed by bdkjones** 2014-02-07 00:26 UTC
