### ISSUE TITLE
Compass error invalid option: --no-sourcemap when trying to compile sass

### ISSUE THREAD

**Issue by jrdn91** [bdkjones/CodeKit2#487] opened 2014-11-12 21:29 UTC
Brief Description:
Since updating to the newest version I'm getting this issue on all my projects now.
When I compile any sass files I see that in the compass output and it can't compile that sass.

Expected Results:
To actually get sass to compile with compass

Actual Results:
Constant error saying sourcemap is not an option.

Link to download ZIP:
https://drive.google.com/open?id=0B-eKT0Z_vxfHbTFZSFlnTk9FRFE&authuser=0

Steps to reproduce:
Just try to compile sass

System info:
latest version of codekit 2.1.9, Mac 10.10 Yosemite, Chrome, I'm trying to use codekits versions of comapss and sass.

**Comment by bdkjones** [comment] 2014-11-12 23:18
Please take a screenshot of the Compilers tab of the Preferences window after selecting Compass in the sidebar.

**Comment by jrdn91** [comment] 2014-11-13 01:20
https://drive.google.com/open?id=0B-eKT0Z_vxfHRmhGS3dhRm9Ncjg&authuser=0

**Comment by simonwimell** [comment] 2014-11-14 10:16
Getting the same error message since updating to 2.1.9. But I'm using Compass executable at /usr/bin/compass

**Comment by jrdn91** [comment] 2014-11-14 12:34
Yeah that's where I was getting it to but after trying to use codekits compiler it keeps telling me to uninstall older versions of compass and sass which I have none of installed. Sorry forgot to mention that.

**Comment by bdkjones** [comment] 2014-11-14 18:33
Your external version needs to be Compass 1.0.1. The command interface for source maps has apparently changed in the pre-release version of Compass 1.1, so it won't work.

**Comment by jrdn91** [comment] 2014-11-14 18:42
Yes my compass version 1.0.1

**Comment by bdkjones** [comment] 2014-11-14 18:43
Please run `compile -h` on that installed version of Compass and post a screenshot of the output.

**Comment by jrdn91** [comment] 2014-11-14 18:46
```
Ignoring atomic-1.1.14 because its extensions are not built.  Try: gem pristine atomic-1.1.14
Ignoring eventmachine-1.0.3 because its extensions are not built.  Try: gem pristine eventmachine-1.0.3
Ignoring thin-1.6.0 because its extensions are not built.  Try: gem pristine thin-1.6.0
Ignoring thin-1.6.0 because its extensions are not built.  Try: gem pristine thin-1.6.0

Usage: compass compile [path/to/project] [path/to/project/src/file.sass ...] [options]

Description:
compile project at the path specified or the current directory if not specified.

Options:
        --[no-]sourcemap             Generate a sourcemap during compilation.
        --time                       Display compilation times.
        --debug-info                 Turns on sass's debuging information
        --no-debug-info              Turns off sass's debuging information
    -r, --require LIBRARY            Require the given ruby LIBRARY before running commands.
                                       This is used to access compass plugins without having a
                                       project configuration file.
    -l, --load FRAMEWORK_DIR         Load the framework or extensions found in the FRAMEWORK directory.
    -L, --load-all FRAMEWORKS_DIR    Load all the frameworks or extensions found in the FRAMEWORKS_DIR directory.
    -I, --import-path IMPORT_PATH    Makes files under the IMPORT_PATH folder findable by Sass's @import directive.
    -q, --quiet                      Quiet mode.
        --trace                      Show a full stacktrace on error
        --force                      Allows compass to overwrite existing files.
        --boring                     Turn off colorized output.
    -c, --config CONFIG_FILE         Specify the location of the configuration file explicitly.
        --app APP                    Tell compass what kind of application it is integrating with. E.g. rails
        --app-dir PATH               The base directory for your application.
        --sass-dir SRC_DIR           The source directory where you keep your sass stylesheets.
        --css-dir CSS_DIR            The target directory where you keep your css stylesheets.
        --images-dir IMAGES_DIR      The directory where you keep your images.
        --javascripts-dir JS_DIR     The directory where you keep your javascripts.
        --fonts-dir FONTS_DIR        The directory where you keep your fonts.
    -e, --environment ENV            Use sensible defaults for your current environment.
                                       One of: development (default), production
    -s, --output-style STYLE         Select a CSS output mode.
                                       One of: nested, expanded, compact, compressed
        --relative-assets            Make compass asset helpers generate relative urls to assets.
        --no-line-comments           Disable line comments.
        --http-path HTTP_PATH        Set this to the root of your project when deployed
        --generated-images-path GENERATED_IMAGES_PATH
                                     The path where you generate your images
    -?, -h, --help                   Show this message

```

**Comment by bdkjones** [comment] 2014-11-14 18:49
Okay. See the top option? Does that not specify `--no-sourcemap` as a valid option? (I'm literally asking; this is not a sarcastic comment.) 

Try checking the `create sourcemap` box in CodeKit's UI for the Sass file in question. Does that work?

/cc @chriseppstein Because I dunno why Compass is rejecting that option.

**Comment by jrdn91** [comment] 2014-11-14 18:55
Yeah it does.

I have it checked and get the error, even if I uncheck it I still get the error, it's weird for sure. I've tried to uninstall compass and reinstall it and it didn't help either, I can try again and maybe specifiy a specific revisions number maybe but it seems like there is something else going on maybe.

**Comment by bdkjones** [comment] 2014-11-14 18:57
I've just looked in the Compass source code and I see under `compass/exec/command_option_parser.rb` that the `--source-map` option is not listed anywhere. It looks like the help documentation shows that as an option but the Compass source code itself does not contain that option. 

I've asked @chriseppstein to let me know what's up and I'll get a fix out as soon as I hear from him.

**Comment by bdkjones** [comment] 2014-11-14 19:04
Try compiling the file from the command line and use the `--no-sourcemap` flag. Does the same error occur? If so, the issue is definitely with Compass.

**Comment by jrdn91** [comment] 2014-11-14 19:11
Running it in the command line works fine both using `--sourcemap` and `--no-sourcemap`

**Comment by bdkjones** [comment] 2014-11-14 20:24
Ok, can you post the _exact_ command you ran in Terminal?

-Bryan

**Comment by jrdn91** [comment] 2014-11-14 21:19
`compass compile --sourcemap` and `compass compile --no-sourcemap`

**Comment by bdkjones** [comment] 2014-11-14 21:38
Please try with a single file. Compass compile [path to project] [path to sass file] [options]

**Comment by bdkjones** [comment] 2014-11-14 22:40
I just tested this over here with CodeKit 2.1.9 by creating a new Compass project. It compiles correctly both with and without the source map box checked. 

Make sure your `config.rb` file does not have any line relating to source maps in it. The Compass API for that command changed in 1.0.1 and if your config.rb file still contains the old one, it will fail.

**Comment by simonwimell** [comment] 2014-11-15 10:58
For me, running the "compass compile" command in terminal works fine. "compass compile --sourcemap" and "compass compile --no-sourcemap" gives error, and compiling with codekit gives error, both with and without "Create a source map" checked. But different error messages, "Error: invalid option: --sourcemap" or "Error: invalid option: --no-sourcemap".

**Comment by simonwimell** [comment] 2014-11-15 10:59
There's no source map mentions in my config.rb.

**Comment by jrdn91** [comment] 2014-11-15 13:16
I don't have a source map mention in my config.rb either, I'm also getting the exact same errors as simonwimell

**Comment by chriseppstein** [comment] 2014-11-17 22:54
There is a change in the Sass command line and API around sourcemaps in Sass 3.4 but the compass CLI has remained unchanged in 1.0 and 1.1.

**Comment by bdkjones** [comment] 2014-11-17 23:02
Thanks Chris. Everyone else: are you sure you're running the latest version of Sass 3.4 if you've switched CodeKit to an external compiler?

**Comment by simonwimell** [comment] 2014-11-18 08:53
I have Sass 3.4.8 and Compass 1.0.1, though when checking "Use CodeKit's internal Sass/Compass", I get "Compass failed to run because your Mac has an older version of Sass and/or Compass installed that conflicts with the newer versions in CodeKit. You must remove all versions of Sass below 3.3.rc6 and all versions of Compass below 1.0.alpha18. Do this at the command line by running 'sudo gem uninstall sass' and 'sudo gem uninstall compass'."

**Comment by simonwimell** [comment] 2014-11-18 09:01
Now I've tried to uninstall sass and compass, and choose to use codekit's internal versions, still getting conflict message.

**Comment by jrdn91** [comment] 2014-11-18 19:32
Same here, I've done the same exact steps as simon

**Comment by bdkjones** [comment] 2014-11-18 22:05
Ok, please zip up the entire project and post a link to download it.

You can omit the pages and images, but I need everything in place related to stylesheets. I need test cases because I can't replicate this behavior over here.

Do you guys have RVM installed? Does everyone seeing this issue have compass/sass gems installed on the command line?

-Bryan

**Comment by iamchrissmith** [comment] 2014-11-19 14:26
I am experiencing the same problem with all of my projects (even brand new dummy ones).

I am still able to use compass watch from the terminal so this seems to be related to CodeKit.  I have tried with both with the internal compiler and the one located at my /usr/bin. I have ensured that my compass and sass are up to date.  

The problem seems to have shown up for me on 11/13/14.  This would have been shortly after the last version of CodeKit came out and shortly after I updated to Yosemite's Pre-release: OS X Update Seed 10.10.1(14B23).

Here is a link to the dummy project I created: https://dl.dropboxusercontent.com/u/13601031/test-codekit.zip

**Comment by jrdn91** [comment] 2014-11-19 15:07
I have RVM installed yes,

Here is the link to my dummy project that has just some basic sass and css compilation needs that I have confirmed still has the sourcemap error issue.

https://drive.google.com/open?id=0B-eKT0Z_vxfHNlB3QnZXalludW8&authuser=0

Much like chris, I can run compass watch with the source map option either in config.rb or by passing it as a terminal flag and all is well in the world.

**Comment by napkindrawing** [comment] 2014-11-19 15:44
Hi All! I've got a fix =)

A coworker of mine had this exact same problem as soon as they'd updated.

I noticed two things that were different between their machine and mine, and after resolving both everything's working again (not sure which one fixed it, sorry):
- They was running `CodeKit.app` _not_ in `/Applications`, so I had them move it there
- Their installed (external to CodeKit) version of compass was `1.0.0.alpha.12` so I manually upgraded that to `1.0.1`.

But they'd set stuff to compile with internal compiler, so I'm assuming it's running `CodeKit.app` not in `/Applications` that caused it.

**Comment by iamchrissmith** [comment] 2014-11-19 15:49
Unfortunately, I have my codekit app in my /Applications folder and when i run:
`~$ compass -v`
I see:
`Compass 1.0.1 (Polaris)`...

**Comment by jrdn91** [comment] 2014-11-19 15:51
Yep same for me, uninstalled both sass and compass and reinstalled forcing the correct versions (just to make sure I wasn't grabbing an alpha or beta version) and still  a no go.

Also what's weird is when I uninstall sass and compass and tell codekit to use it's internal compiler I get this message

```
Compass failed to run because your Mac has an older version of Sass and/or Compass installed that conflicts with the newer versions in CodeKit. You must remove all versions of Sass below 3.3.rc6 and all versions of Compass below 1.0.alpha18. Do this at the command line by running 'sudo gem uninstall sass' and 'sudo gem uninstall compass'.
```

even though when I run `sass -v` or `compass -v` it shows there is nothing installed that can run those commands, meaning sass nor compass are even installed on my system

**Comment by bdkjones** [comment] 2014-11-19 23:47
Okay, BOTH of those test projects you guys posted compiled 100% correctly over here using CodeKit 2.1.9. No issues whatsoever. 

The difference appears to be that I don't have any gems installed on my system. Zero. I think you guys are seeing this problem because you have one or more gems installed that conflict with the ones built into CodeKit. It may not be Compass itself --- it may be a dependency or a totally unrelated gem that's loading weird libraries into Ruby. (This is especially true for @jordan4jc: that error message you got when you uninstalled Sass and Compass happens when Ruby throws a "superclass mismatch" exception. It means there's conflicting gems.)

## NUKE EVERYTHING

Bottom line: the sure-fire way to fix this issue is to NUKE ALL THE GEMS. 

Uninstall every gem you have. All of 'em. Then, go to /Library/Ruby/Gems/2.0.0/ and make sure that folder is totally empty. All the cached versions of gems, all the docs, all the specs, everything: nuke it all. If you have older versions of Ruby listed in that folder (like 1.8 if you upgraded from Mountain Lion or 1.9 if you upgraded from Mavericks), nuke that crap too. 

Then, reboot.

Then, run `sudo gem update --system` on the command line. If you're using a Ruby version manager like RVM, nuke all that stuff too and switch the environment back to the system default before you do. 

Essentially, the goal is to get Ruby to a 100% clean state. Then, test again. CodeKit should compile just fine. At that point, you can reinstall the gems you had on your system until you find the one that causes the conflict.

I know that's a really complex, shitty approach to debugging, but it's the only sure-fire way I know of to fix this issue short of doing a 100% clean install of Yosemite. 

## Also:

Ruby blows. If I could punch everyone responsible for that shitty, shitty language I would do so gladly. The sooner the world drops Ruby, the better off we will all be.

**Comment by simonwimell** [comment] 2014-11-20 09:32
Yes, I'm using RVM, and now I finally managed to update and install the right version as it seems. Now I can use both Sass/Compass executables and CodeKit's internal compiler.

**Closed as completed** 2015-01-24 06:42 UTC
