### ISSUE TITLE
Improper drawing in the Sass file processing view

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#18] opened 2013-12-18 12:12 UTC
Again an, i guess 10.8 related, issue. 

![sassabout](https://f.cloud.github.com/assets/1665422/1772991/848cf4b6-67dd-11e3-8910-963fe23647b2.png)

**Comment by bdkjones** [comment] 2013-12-18 18:58
Damn. Something weird is going on with 10.8. I'm going to have to install it and test.

**Comment by bdkjones** [comment] 2013-12-27 05:12
Have you been able to reproduce this? Has anyone else seen the same thing on 10.8? I can't reproduce this on my end.

**Comment by bdkjones** [comment] 2013-12-27 23:00
Right. Haven't heard back. Going to call this a one-off.

**Comment by rpkoller** [comment] 2013-12-31 17:57
Tried with Beta4 again. The issue is still valid on 10.8.5

![bildschirmfoto 2013-12-31 um 18 55 29](https://f.cloud.github.com/assets/1665422/1827898/fb840c0a-7244-11e3-9794-3c4a4ce99250.png)

**Comment by rpkoller** [comment] 2013-12-31 18:18
I tried Autoprefixer too. Then the visual representation on the output file is out of step too:
![bildschirmfoto 2013-12-31 um 19 16 55](https://f.cloud.github.com/assets/1665422/1827977/edfce64e-7247-11e3-91ee-52a6165409d3.png)

**Comment by rpkoller** [comment] 2014-01-01 15:20
another display issue on 10.8

![bildschirmfoto 2014-01-01 um 16 18 18](https://f.cloud.github.com/assets/1665422/1829754/39547bd8-72f8-11e3-8715-44c54d6a0960.png)

**Comment by bdkjones** [comment] 2014-01-01 20:40
How ancient is your Mac? Are you _ABSOLUTELY_ sure you're running the latest beta?

**Comment by rpkoller** [comment] 2014-01-02 00:20
mbp 13" early 2011 with 10.8.5 all the latest patches applied. and am quite sure that i am running the latest beta. just re-downloaded beta 4 and replaced the current version the screenshots are from. but still version 2.0 (15773) with the date stamp Friday, 27. December 2013 06:18  - identical version :/

**Comment by bdkjones** [comment] 2014-01-02 22:33
Okay, this _should_ be resolved in Beta 5. Let me know once I post it.

**Comment by rpkoller** [comment] 2014-01-03 09:39
I think you could remove "(hopefully)" from the changelog ;) 

![bildschirmfoto 2014-01-03 um 10 33 43](https://f.cloud.github.com/assets/1665422/1838379/bf80f322-745a-11e3-843f-07f59b0a568a.png)
![bildschirmfoto 2014-01-03 um 10 34 00](https://f.cloud.github.com/assets/1665422/1838380/c49da7ba-745a-11e3-95c3-356ce104dea9.png)
![bildschirmfoto 2014-01-03 um 10 34 15](https://f.cloud.github.com/assets/1665422/1838381/c8846bfc-745a-11e3-97cb-0784b4ced2c4.png)

**Comment by rpkoller** [comment] 2014-01-11 22:47
ooooooops i've missed one to report. caught this one today in beta 8: 
![bildschirmfoto 2014-01-11 um 23 42 44](https://f.cloud.github.com/assets/1665422/1895101/416b2e94-7b12-11e3-99fe-8f370c0d7fc6.png)

**Closed as completed** 2014-01-12 00:31 UTC
Labels: ✘✘, [A] User Interface, [P] Confirmed

**Comment by rpkoller** [comment] 2014-01-18 09:27
@bdkjones the webpage icon is still out of step in beta 11

**Comment by rpkoller** [comment] 2014-01-28 18:05
@bdkjones looks fine now in beta 13. thanks!
![bildschirmfoto 2014-01-28 um 19 03 59](https://f.cloud.github.com/assets/1665422/2021957/b1e3111e-8846-11e3-8c6c-b89d78697b5b.png)

**Comment by rpkoller** [comment] 2014-02-02 00:13
@bdkjones uhhh in beta 14 the layout is wrong again :/  
![bildschirmfoto 2014-02-02 um 01 12 28](https://f.cloud.github.com/assets/1665422/2059219/d6a456ce-8b9e-11e3-9a96-c0352882a581.png)

**Comment by bdkjones** [comment] 2014-02-02 01:07
How ancient is your Mac?

**Comment by rpkoller** [comment] 2014-02-02 09:38
haha you already asked that question ;) and i am still running a mbp 13" early 2011 with 10.8.5 ;)

**Comment by rpkoller** [comment] 2014-02-05 10:43
@bdkjones still out of step in beta 15

**Comment by bdkjones** [comment] 2014-02-05 11:03
I give up, man. Upgrade to Mavericks.

**Comment by rpkoller** [comment] 2014-02-05 23:11
It's ok. the only thing about is that it works in one beta and then not anymore in another. 

And yeah sooner or later  i will update to Mavericks - as soon as i have a second computer at home again i can use as server. But if i would upgrade right now i would have to use iCloud to sync my adresses and calender events with my iphone cuz the local sync was kicked "thanks" to apple and that won't gonna happen. ;)  So i have to wait and stick to 10.8 :(

**Comment by rpkoller** [comment] 2014-02-16 14:16
@bdkjones fyi in beta 17 it is working again ;) 
![bildschirmfoto 2014-02-16 um 15 15 54](https://f.cloud.github.com/assets/1665422/2180363/f30daaa0-9714-11e3-82b9-017514a0783a.png)
