### ISSUE TITLE
Infinite LESS compilation

### ISSUE THREAD

**Issue by devilskitchen** [bdkjones/CodeKit2#71] opened 2013-12-20 12:08 UTC
When saving a LESS file (with numerous imports), Growl tells me that it has compiled successfully—twice. Then the whirly at the bottom of the CodeKit screen tells me that it is compiling style.less forever, and ever. Until I quit CK2.

![screen shot 2013-12-20 at 12 04 01](https://f.cloud.github.com/assets/1190864/1790210/53be21c8-696f-11e3-888c-2389ced45449.png)

This happens every time.

**Comment by marcaube** [comment] 2013-12-20 12:24
The same happened in #41

**Comment by bdkjones** [comment] 2013-12-22 08:37
Please zip the project, put it online and post a link here so I can test with it. Also, what editor are you saving the file in?

**Comment by devilskitchen** [comment] 2013-12-22 14:43
I'ev saving the file using Coda. Posting the project might be a little difficult (for legal/business reasons rather than technical, but I'll see what I can do).

Otherwise, I'll see if the same thing happens in a different project.

**Comment by mdavis1982** [comment] 2013-12-23 11:19
This is a duplicate of #41.

**Closed as completed by mdavis1982** 2013-12-23 11:19 UTC
Labels: [S] Rejected, ✘✘, [A] Processor
