### ISSUE TITLE
CK2 is producing errors when I use it's internal Compass compiler.

### ISSUE THREAD

**Issue by frankyonnetti** [bdkjones/CodeKit2#50] opened 2013-12-19 00:50 UTC
If I use CK2's internal Compass compiler I get these errors:

```
Compass was unable to compile one or more files in the project: 
/Library/Ruby/Gems/2.0.0/gems/sass-3.2.12/lib/sass/script/literal.rb:7:in `<module:Script>': superclass mismatch for class Literal (TypeError)
  from /Library/Ruby/Gems/2.0.0/gems/sass-3.2.12/lib/sass/script/literal.rb:1:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:2:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
  from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
  from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
  from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
  from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
  from /Applications/CodeKit2 beta/CodeKit.app/Contents/Resources/engines/compass/bin/compass:32:in `block in <main>'
  from /Applications/CodeKit2 beta/CodeKit.app/Contents/Resources/engines/compass/bin/compass:20:in `fallback_load_path'
  from /Applications/CodeKit2 beta/CodeKit.app/Contents/Resources/engines/compass/bin/compass:31:in `<main>'
```

But, if I set it to use my local excutable path to `/usr/bin/compass`, (under preferences) no errors and all compiles as expected.

**Comment by rpkoller** [comment] 2013-12-19 01:02
Is it possible that you try to require some compass plugins within your config.rb project file? Due to dependencies, plugins are unable to be included in the internal Compass Codekit version and instead you have to run the external local one as you described.

**Comment by maxlapides** [comment] 2013-12-19 01:10
This is a duplicate of this issue: https://github.com/bdkjones/codekit2beta/issues/11

**Comment by frankyonnetti** [comment] 2013-12-19 01:21
@rpkoller no, because if I create a fresh/new compass project I get the same results.

**Comment by WebInspectInc** [comment] 2013-12-19 04:21
I’m having a very similar issue. It fails when adding a new Compass project. Testing further.

**Comment by mdavis1982** [comment] 2013-12-19 08:28
This is related to the internal pre-release version of Compass and SASS being used. It's the same issue as #11. Closing this issue.

**Closed as completed by mdavis1982** 2013-12-19 08:28 UTC
Labels: [S] Rejected
