### ISSUE TITLE
Feature Request: Custom project icons

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#103] opened 2013-12-28 13:45 UTC
This might already be an option that I've missed, but it would be nice to be able to select custom icons for each project. (Even nicer would be for CK2 to automatically use any touch icons that were in the project's root subpath.)

**Comment by mdavis1982** [comment] 2013-12-29 23:32
This is a duplicate of #20.

**Closed as completed** 2013-12-29 23:32 UTC
Labels: [S] Rejected, ✔✔, [A] Projects
