### ISSUE TITLE
Warning about WebSocket extension in console

### ISSUE THREAD

**Issue by Andreyco** [bdkjones/CodeKit2#274] opened 2014-02-25 12:11 UTC
I get this warning `WebSocket extension "x-webkit-deflate-frame" is deprecated` in console, caused by injected JavaScript file.

Would be nice, to get that removed. Despite that, low priority :)

Thanks!

**Comment by bdkjones** [comment] 2014-02-25 20:58
That's not related to CodeKit; I don't that in the refresh script and I don't get the same deprecation warning in my console when running in Safari. I think it's something in your project.

**Comment by Andreyco** [comment] 2014-02-26 14:01
Sorry, I was not specific about browser.
I use Chrome, this started to happen after I upgraded to version 33 I think. I can confirm Safari does not print anything in console.

I still think this is related to CK2, despite the fact, you are not dealing with "x-webkit-deflate-frame" directly.

![screen shot 2014-02-26 at 14 51 20](https://f.cloud.github.com/assets/829963/2270428/25ea88aa-9eed-11e3-9073-a59eaa05e438.png)

Content of whole project is as simple as this.

``` html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    Test
</body>
</html>
```

If you think, this is no problem, feel free to close the issue again. I just don't want CK2 stop working once the extension is removed completely (or something else).

Thank you! :)

**Comment by rasmusbe** [comment] 2014-02-26 20:18
I can confirm this, and I agree this is not a problem, Chrome is warning way to much.

But I did expand the javascript file giving this error and it seems like this line gives the warning,
`
e === !0 ? (ckSocketConnectionAttempts++, n = new WebSocket(ckrphnba, "ckrp")) : (ckSocketConnectionAttempts++, n = new WebSocket(ckrphna, "ckrp")), n.onopen = function () {
`
![screenshot 2014-02-26 21 16 42](https://f.cloud.github.com/assets/2124386/2274996/f0c89028-9f22-11e3-8a2a-5a4d63ef5785.png)

But I would still recommend you to close the issue since it's just Chrome being overcautious.

Update:
Chromium also have an issue about removing this warning:
https://codereview.chromium.org/181303002/

**Comment by bdkjones** [comment] 2014-02-27 01:37
Yea, this sounds like a Chrome issue. 

The syntax I'm using the open a websocket IS the standard syntax. There's nothing else for me to do.

**Comment by bdkjones** [comment] 2014-02-27 06:56
Here's the line of code that creates the websocket: 

```
window.WebSocket = window.WebSocket || window.MozWebSocket;
```

If any of you know what I need to change in that line to make Chrome shut the hell up, I'm all ears. As far as I know, this is the standard way to create a websocket.

**Closed as completed** 2014-02-27 07:20 UTC
