### ISSUE TITLE
Compass fails to install (beta 9 & beta 10)

### ISSUE THREAD

**Issue by hartless** [bdkjones/CodeKit2#157] opened 2014-01-14 19:16 UTC
1. Launch CK2b9 with Shift key
2. add new (empty) folder
3. click Project Settings gear icon
4. Frameworks > Compass... install Compass button
5. Confirm by pressing Proceed button in dialog
6. CK Error: 
   ArgumentError on line ["137"] of /Applications/CodeKit.app/Contents/Resources/engines/compass/compass-core/lib/compass/configuration.rb: Invalid argument: {:project_path=>"/Users/hartbr/Desktop/cktestcompass"}
   Run with --trace to see the full backtrace

![image](https://f.cloud.github.com/assets/1090636/1914083/7baefa94-7d52-11e3-8196-e9a86434d175.png)

**Comment by bdkjones** [comment] 2014-01-15 04:52
Fixed in Beta 10.

**Comment by hartless** [comment] 2014-01-15 18:28
Same issue in Beta 10.

**Comment by bdkjones** [comment] 2014-01-16 02:53
Are you POSITIVE that you're using CodeKit's built-in version of Compass? You have NOT switched the app to an external Compass compiler? Show me a screenshot of the Compass section of the "advanced" tab in preferences, please.

I can't replicate this issue over here.

**Comment by bdkjones** [comment] 2014-01-16 05:23
Also, are you sure that you have valid write permissions to the folder you're attempting to install Compass into? Is that folder on a remote disk?

**Comment by tombonez** [comment] 2014-01-16 08:29
After going from beta 8 to beta 10 the same thing has happened to me. My Macs permissions have completely screwed up too :/

**Comment by marpala** [comment] 2014-01-16 11:24
Codekit Beta 10 (fresh install). I got this error:

```
/Library/Ruby/Gems/2.0.0/gems/sass-3.2.12/lib/sass/script/literal.rb:7:in `<module:Script>': superclass mismatch for class Literal (TypeError)
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.2.12/lib/sass/script/literal.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:2:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/compass/bin/compass:43:in `block in <main>'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/compass/bin/compass:31:in `fallback_load_path'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/compass/bin/compass:42:in `<main>'
```

![screen shot 2014-01-16 at 12 21 12](https://f.cloud.github.com/assets/439204/1929937/5b02766e-7ea0-11e3-8d5c-f04cc2ca9ab8.png)

**Comment by hartless** [comment] 2014-01-16 18:52
@bdkjones - yes, Internal compiler. Standard permissions - created new folder on Desktop, drag to Codekit. 

![image](https://f.cloud.github.com/assets/1090636/1933681/3d4f5058-7edf-11e3-8b3b-f93ae72239b6.png)

**Comment by bdkjones** [comment] 2014-01-31 07:41
I can't replicate this on my machine. Is anyone else still seeing this behavior with the latest beta?

**Comment by ChristiaanKZ** [comment] 2014-02-01 17:19
Nope I don't

**Comment by bdkjones** [comment] 2014-02-02 02:43
I can't reproduce this and I haven't heard anything, so closing.

**Closed as completed by bdkjones** 2014-02-02 02:43 UTC
Labels: [A] Frameworks

**Comment by hartless** [comment] 2014-03-14 14:08
@bdkjones Just an FYI. I was still getting this error yesterday, managed to track it down to my Ruby Gems folder. I renamed the folder "2.0.0" to "2.0" and that resolved the error. May have been from a fresh install of Ruby instead of the standard OS X install.
