### ISSUE TITLE
Feature request: custom project icons

### ISSUE THREAD

**Issue by jakepetroules** [bdkjones/CodeKit2#177] opened 2014-01-19 13:07 UTC
This is a small one but it should be doable. And/or display 'favicon.ico' in the list of available icon selections if one is present in that project's root directory.

**Comment by noahfrederick** [comment] 2014-01-19 19:16
This is a duplicate of #20 (and #103 which has an identical title, by the way). You can search previous issues through the search box at the top of the page.

**Closed as completed by noahfrederick** 2014-01-19 19:16 UTC
Labels: [A] User Interface

**Comment by jakepetroules** [comment] 2014-01-19 19:17
Sorry, missed those.
