### ISSUE TITLE
Duplicate Sass Compiles

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#98] opened 2013-12-26 23:07 UTC
I'm having an issue where my Sass files are being compiled multiple times. I'm not sure if this has anything to do with it, but the issue occurs whenever I save either the Sass partials or when I save the Sass files that import the partials. This is an issue on a couple of projects that I'm working on - both are WordPress, one uses Compass, the other doesn't. I'm on Mavericks 10.9.1 and I'm using Coda 2, but the issue also occurs when I save a Sass file using TextEdit. Please let me know if you need any more information!

**Comment by maxlapides** [comment] 2013-12-26 23:15
This also relates to the overlapping text issue I filed earlier: https://github.com/bdkjones/codekit2beta/issues/63

The overlapping text occurs on the duplicate compile.

**Comment by bdkjones** [comment] 2013-12-27 01:18
Please zip one of these projects and send it my way so I can test with it.

-Bryan

**Comment by maxlapides** [comment] 2013-12-27 01:21
Sure, here it is!
http://maxlapides.com/downloads/maxlapides.zip

**Comment by bdkjones** [comment] 2013-12-27 23:56
When you say "compile multiple times" do you mean that when you save a partial like `_variables.scss`, you see that both `ie.scss` and `style.scss` compile? Or do you mean that the SAME sass file is compiling twice in a row (i.e. `style.scss` compiles twice)? 

If the former, that's absolutely the correct behavior for the project you posted.

**Comment by maxlapides** [comment] 2013-12-27 23:59
It's actually the latter: when I save `_variables.scss`, both `ie.scss` and `style.scss` compile twice. For example, I just cleared my CK log and then saved `_variables.scss` once. Here's the output:

![2013-12-27_18-57-07](https://f.cloud.github.com/assets/1874682/1816822/c5a45d14-6f52-11e3-8cba-088181184d5c.png)

**Comment by bdkjones** [comment] 2013-12-28 00:33
I see. I need all the details you can give me about this.

-- Is the folder local? Network disk?
-- Is anything else watching the folder? Dropbox, some syncing client, FTP app?
-- Is anything else modifying the files? Applescript, Coda set to do something funky on file saves?
-- What apps are running on your machine?
-- What format is this disk using?

Every detail you can get me. Something is different on your machine and I'm not sure what that is.

**Comment by maxlapides** [comment] 2013-12-28 02:34
Sure:

-- The folder is local, not a network disk. It's in Applications/MAMP/htdocs
-- Nothing else is watching the folder - I even tried quitting Dropbox, Google Drive, and Coda 2 just to be sure.
-- Nothing else should be modifying the files.
-- For testing purposes, I quit all of my applications. I'm just running Safari, CodeKit, and TextEdit and I'm still getting duplicate compiles. Other than that, the applications running in my menu bar are Adobe Creative Cloud, Fantastical, LogMeIn, Living Earth, EarthDesk, Should I Sleep, 1Password, and Mint.
-- My internal hard drive is formatted Mac OS Extended (Journaled, Encrypted). It's the solid state hard drive that came with my rMBP.

And some other details:

-- I'm using MAMP Pro, but the issue remains even when the MAMP Pro servers are off and the MAMP Pro application isn't running.
-- I restarted my computer and the issue persists.

If you like, I'd be happy to set up a join.me so you can look around my computer yourself?

**Comment by bdkjones** [comment] 2013-12-28 03:34
Ok. I've been able to reproduce this in Coda 2.5

I'm looking into it.

**Comment by bdkjones** [comment] 2014-01-02 22:14
This is fixed in Beta 5.

NOTE: as a result, CodeKit will now respond to a file-save event only once every 1.5 seconds. If you save a file more rapidly than that, CodeKit will ignore every save event until 1.5 seconds have elapsed since the last save event that it responded to.

**Closed as completed by bdkjones** 2014-01-02 22:14 UTC
Labels: ✘✘, [P] Confirmed, [A] Processor
