### ISSUE TITLE
Beta 8 Project Settings Weirdness

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#143] opened 2014-01-11 21:19 UTC
Was trying to verify/check fix for #108 and #124 and saw some definite weirdness. Here are the steps.
1. Launched CKb8
2. Project Settings -> JSHint
3. jQuery is selected! (I could swear I successfully de-selected it in the past, so this might be a bug as well, but I can be absolutely certain.)
4. De-select jQuery
5. Close Project Settings
6. Here's where the weirdness starts: Click Project Settings gear icon. It turns gold, but nothing else happens. The rest of the UI shows the same old file listing.
7. Click the Project Settings gear icon again. Here's the result:

![screen shot 2014-01-11 at 4 10 04 pm](https://f.cloud.github.com/assets/1731910/1894907/d12a1764-7b05-11e3-8a33-50051a24fdbb.png)

Quitting and restarting and everything seems okay. Even jQuery is de-selected (yeah!).

**Comment by bdkjones** [comment] 2014-01-11 21:22
Duplicate of #141

**Closed as completed by bdkjones** 2014-01-11 21:22 UTC
