### ISSUE TITLE
Browser refresh extremely slow with External server and CodeIgniter

### ISSUE THREAD

**Issue by eberth** [bdkjones/CodeKit2#256] opened 2014-02-14 21:55 UTC
I created a new Foundation project using command line, then I added the folder to codekit and everything worked fine. Then I downloaded CodeIgniter and copied the files to the same folder and started setting up a simple site. Then I turned on the external server with MAMP and changed the project settings. The site loads very slow and the progress bar is stuck in the middle permanently. Whenever I make changes to the files the browser restarts the refresh process but it's way too slow..

![screen shot 2014-02-14 at 15 51 51](https://f.cloud.github.com/assets/41636/2175603/8fe2a4ba-95c2-11e3-8e18-23fea074d595.png)

**Comment by bdkjones** [comment] 2014-02-16 01:30
Screencast and demo project. Post both here.

**Comment by bdkjones** [comment] 2014-02-16 02:55
Also, remove the trailing slash from your Preview Path entry. That may be the cause.

**Comment by C-Benz** [comment] 2014-02-16 05:02
I've wondered too when to use a slash at the beginning or end of the website root subpath, external server address, and preview subpath fields. What's the best practice?

**Comment by bdkjones** [comment] 2014-02-16 05:25
It depends on what your server is set up to handle. Wordpress, for instance, redirects trailing slash URLs to the their non-slashed counterparts. That slows down the page load. MAMP tends to have an issue with trailing slashes, often taking 30-40 seconds to resolve a URL.

**Comment by eberth** [comment] 2014-02-16 05:55
I removed the trailing slash and it made no difference.

Here's a sample video and the project..

https://dl.dropboxusercontent.com/u/146323/codekit/codekit-codeigniter.mp4

https://dl.dropboxusercontent.com/u/146323/codekit/overflow14.zip

**Comment by bdkjones** [comment] 2014-03-14 04:27
Do you have Internet Sharing enabled on your Mac? If so, turn it off.

**Comment by bdkjones** [comment] 2014-04-04 03:18
Disabling Internet Sharing is the fix for this.

**Closed as completed by bdkjones** 2014-04-04 03:18 UTC

**Comment by Shiva127** [comment] 2014-09-24 04:59
No other solution than turn off Internet Sharing?

To be clear: it resolve the problem. But I also need the Internet Sharing…

**Comment by bdkjones** [comment] 2014-09-24 05:33
Not currently. I can't get Apple to tell me why Internet Sharing slows down Bonjour name resolution.

**Comment by repoman** [comment] 2015-01-15 13:08
I’m having this problem too, and Internet Sharing is not on. It seems like GET requests are normal, but POST requests are super slow.
